// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1

type CatalogExpansion interface{}

type ConnectorExpansion interface{}

type EnvironmentExpansion interface{}

type FileExampleExpansion interface{}

type ProjectExpansion interface{}

type ResourceExpansion interface{}

type ResourceDefinitionExpansion interface{}

type SettingExpansion interface{}

type TemplateExpansion interface{}

type TemplateCompletionExpansion interface{}

type TemplateCompletionExampleExpansion interface{}

type VariableExpansion interface{}
