apiVersion: 1

datasources:
  - name: "DS_PROMETHEUS"
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      manageAlerts:
      prometheusType: Prometheus
      prometheusVersion: 2.44.0
      incrementalQuerying: true
      incrementalQueryOverlapWindow: 10m
      cacheLevel: 'High'

