run:
  timeout: 10m
  tests: true

linters:
  disable-all: true
  enable:
    - ineffassign
    - staticcheck
    - stylecheck
    - typecheck
    - durationcheck
    - asciicheck
    - errcheck
    - bidichk
    - durationcheck
    - errcheck
    - unused
    - nilerr
    - gocritic
    - gosimple
    - govet
    - gosec
    - revive
    - errname
    - errorlint
    - misspell

linters-settings:
  staticcheck:
    checks: [ "all","-SA1019","-SA2002" ]
  stylecheck:
    checks: [ "all","-ST1003" ]
  gosec:
    severity: "low"
    confidence: "low"
    excludes:
      - G101
      - G112
  revive:
    rules:
      - name: var-naming
        disabled: true
        arguments:
          - [ "HTTP", "ID", "TLS", "TCP", "UDP", "API", "CA", "URL", "DNS" ]

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - rowserrcheck
        - makezero

