// SPDX-FileCopyrightText: 2023 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "ent". DO NOT EDIT.

package model

import "context"

// ClientSet is an interface that allows getting all clients.
type ClientSet interface {
	// AllocationCosts returns the client for interacting with the AllocationCost builders.
	AllocationCosts() *AllocationCostClient

	// ClusterCosts returns the client for interacting with the ClusterCost builders.
	ClusterCosts() *ClusterCostClient

	// Connectors returns the client for interacting with the Connector builders.
	Connectors() *ConnectorClient

	// Environments returns the client for interacting with the Environment builders.
	Environments() *EnvironmentClient

	// EnvironmentConnectorRelationships returns the client for interacting with the EnvironmentConnectorRelationship builders.
	EnvironmentConnectorRelationships() *EnvironmentConnectorRelationshipClient

	// Perspectives returns the client for interacting with the Perspective builders.
	Perspectives() *PerspectiveClient

	// Projects returns the client for interacting with the Project builders.
	Projects() *ProjectClient

	// Roles returns the client for interacting with the Role builders.
	Roles() *RoleClient

	// Secrets returns the client for interacting with the Secret builders.
	Secrets() *SecretClient

	// Services returns the client for interacting with the Service builders.
	Services() *ServiceClient

	// ServiceDependencies returns the client for interacting with the ServiceDependency builders.
	ServiceDependencies() *ServiceDependencyClient

	// ServiceResources returns the client for interacting with the ServiceResource builders.
	ServiceResources() *ServiceResourceClient

	// ServiceRevisions returns the client for interacting with the ServiceRevision builders.
	ServiceRevisions() *ServiceRevisionClient

	// Settings returns the client for interacting with the Setting builders.
	Settings() *SettingClient

	// Subjects returns the client for interacting with the Subject builders.
	Subjects() *SubjectClient

	// SubjectRoleRelationships returns the client for interacting with the SubjectRoleRelationship builders.
	SubjectRoleRelationships() *SubjectRoleRelationshipClient

	// Templates returns the client for interacting with the Template builders.
	Templates() *TemplateClient

	// TemplateVersions returns the client for interacting with the TemplateVersion builders.
	TemplateVersions() *TemplateVersionClient

	// Tokens returns the client for interacting with the Token builders.
	Tokens() *TokenClient

	// WithTx gives a new transactional client in the callback function,
	// if already in a transaction, this will keep in the same transaction.
	WithTx(context.Context, func(tx *Tx) error) error

	// Dialect returns the dialect name of the driver.
	Dialect() string

	// Debug returns the debug mode of the client.
	Debug() *Client

	// Use adds the mutation hooks to all the entity clients.
	Use(...Hook)
}

// AllocationCostClientGetter is an interface that allows getting AllocationCostClient.
type AllocationCostClientGetter interface {
	// AllocationCosts returns the client for interacting with the AllocationCost builders.
	AllocationCosts() *AllocationCostClient
}

// ClusterCostClientGetter is an interface that allows getting ClusterCostClient.
type ClusterCostClientGetter interface {
	// ClusterCosts returns the client for interacting with the ClusterCost builders.
	ClusterCosts() *ClusterCostClient
}

// ConnectorClientGetter is an interface that allows getting ConnectorClient.
type ConnectorClientGetter interface {
	// Connectors returns the client for interacting with the Connector builders.
	Connectors() *ConnectorClient
}

// EnvironmentClientGetter is an interface that allows getting EnvironmentClient.
type EnvironmentClientGetter interface {
	// Environments returns the client for interacting with the Environment builders.
	Environments() *EnvironmentClient
}

// EnvironmentConnectorRelationshipClientGetter is an interface that allows getting EnvironmentConnectorRelationshipClient.
type EnvironmentConnectorRelationshipClientGetter interface {
	// EnvironmentConnectorRelationships returns the client for interacting with the EnvironmentConnectorRelationship builders.
	EnvironmentConnectorRelationships() *EnvironmentConnectorRelationshipClient
}

// PerspectiveClientGetter is an interface that allows getting PerspectiveClient.
type PerspectiveClientGetter interface {
	// Perspectives returns the client for interacting with the Perspective builders.
	Perspectives() *PerspectiveClient
}

// ProjectClientGetter is an interface that allows getting ProjectClient.
type ProjectClientGetter interface {
	// Projects returns the client for interacting with the Project builders.
	Projects() *ProjectClient
}

// RoleClientGetter is an interface that allows getting RoleClient.
type RoleClientGetter interface {
	// Roles returns the client for interacting with the Role builders.
	Roles() *RoleClient
}

// SecretClientGetter is an interface that allows getting SecretClient.
type SecretClientGetter interface {
	// Secrets returns the client for interacting with the Secret builders.
	Secrets() *SecretClient
}

// ServiceClientGetter is an interface that allows getting ServiceClient.
type ServiceClientGetter interface {
	// Services returns the client for interacting with the Service builders.
	Services() *ServiceClient
}

// ServiceDependencyClientGetter is an interface that allows getting ServiceDependencyClient.
type ServiceDependencyClientGetter interface {
	// ServiceDependencies returns the client for interacting with the ServiceDependency builders.
	ServiceDependencies() *ServiceDependencyClient
}

// ServiceResourceClientGetter is an interface that allows getting ServiceResourceClient.
type ServiceResourceClientGetter interface {
	// ServiceResources returns the client for interacting with the ServiceResource builders.
	ServiceResources() *ServiceResourceClient
}

// ServiceRevisionClientGetter is an interface that allows getting ServiceRevisionClient.
type ServiceRevisionClientGetter interface {
	// ServiceRevisions returns the client for interacting with the ServiceRevision builders.
	ServiceRevisions() *ServiceRevisionClient
}

// SettingClientGetter is an interface that allows getting SettingClient.
type SettingClientGetter interface {
	// Settings returns the client for interacting with the Setting builders.
	Settings() *SettingClient
}

// SubjectClientGetter is an interface that allows getting SubjectClient.
type SubjectClientGetter interface {
	// Subjects returns the client for interacting with the Subject builders.
	Subjects() *SubjectClient
}

// SubjectRoleRelationshipClientGetter is an interface that allows getting SubjectRoleRelationshipClient.
type SubjectRoleRelationshipClientGetter interface {
	// SubjectRoleRelationships returns the client for interacting with the SubjectRoleRelationship builders.
	SubjectRoleRelationships() *SubjectRoleRelationshipClient
}

// TemplateClientGetter is an interface that allows getting TemplateClient.
type TemplateClientGetter interface {
	// Templates returns the client for interacting with the Template builders.
	Templates() *TemplateClient
}

// TemplateVersionClientGetter is an interface that allows getting TemplateVersionClient.
type TemplateVersionClientGetter interface {
	// TemplateVersions returns the client for interacting with the TemplateVersion builders.
	TemplateVersions() *TemplateVersionClient
}

// TokenClientGetter is an interface that allows getting TokenClient.
type TokenClientGetter interface {
	// Tokens returns the client for interacting with the Token builders.
	Tokens() *TokenClient
}
