global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: seal
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: [ "seal" ]
  - job_name: casdoor
    metrics_path: /api/metrics
    static_configs:
      - targets: [ "casdoor:8000" ]
  - job_name: prometheus
    static_configs:
      - targets: [ "prometheus:9090" ]
  - job_name: grafana
    static_configs:
      - targets: [ "grafana:3000" ]
