// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1

// ProjectSpecApplyConfiguration represents an declarative configuration of the ProjectSpec type for use
// with apply.
type ProjectSpecApplyConfiguration struct {
	DisplayName *string `json:"displayName,omitempty"`
	Description *string `json:"description,omitempty"`
}

// ProjectSpecApplyConfiguration constructs an declarative configuration of the ProjectSpec type for use with
// apply.
func ProjectSpec() *ProjectSpecApplyConfiguration {
	return &ProjectSpecApplyConfiguration{}
}

// WithDisplayName sets the DisplayName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisplayName field is set to the value of the last call.
func (b *ProjectSpecApplyConfiguration) WithDisplayName(value string) *ProjectSpecApplyConfiguration {
	b.DisplayName = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *ProjectSpecApplyConfiguration) WithDescription(value string) *ProjectSpecApplyConfiguration {
	b.Description = &value
	return b
}
