name: Clean

permissions:
  contents: write
  pull-requests: read
  actions: write

defaults:
  run:
    shell: bash

on:
  pull_request:
    types:
      - closed

jobs:
  clean:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Remove Publish Result
        uses: actions/github-script@v6
        with:
          # clean up caches created by the pull request itself,
          # ref to https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries,
          # and https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache.
          script: |
            const ref = 'refs/pull/${{ github.event.pull_request.number }}/merge'
            
            console.debug("getting cache list...")
            const cs = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: ref
            });
            console.log("got cache list")
            
            for (const c of cs.data.actions_caches) {
              console.debug(`cleaning cache "${c.key}"...`)
              await github.rest.actions.deleteActionsCacheByKey({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: ref,
                key: c.key
              })
              console.log(`cleaned cache "${c.key}"`)
            }
        continue-on-error: true
