{
 "title": "Seal",
 "description": "Seal Metrics",
 "tags": [ "seal" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "seal" },
   {
    "name": "request_method",
    "label": "Request Method",
    "query": {
     "query": "label_values(api_request_inflight,method)"
    }
   },
   {
    "name": "cron_job",
    "label": "Cron Job",
    "query": {
     "query": "label_values(cron_scheduling_jobs,exported_job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Inflight Request",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(api_request_inflight{job=\"$job\",path=~\"/v1/.*|/account/.*\"}[$__interval])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(api_request_total{job=\"$job\",path=~\"/v1/.*|/account/.*\"}[$__rate_interval])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Goroutine Pool",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(go_pool_in_use_workers{job=\"$job\"} + go_pool_idle_workers{job=\"$job\"}) / go_pool_max_workers{job=\"$job\"} * 100",
       "legendFormat": "open"
      },
      {
       "expr": "go_pool_in_use_workers{job=\"$job\"} / go_pool_max_workers{job=\"$job\"} * 100",
       "legendFormat": "in_use"
      },
      {
       "expr": "go_pool_waiting_tasks{job=\"$job\"} / go_pool_max_tasks{job=\"$job\"} * 100",
       "legendFormat": "block"
      }
     ]
    },
    {
     "title": "Database Pool",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "go_sql_open_connections{job=\"$job\"} / go_sql_max_open_connections{job=\"$job\"} * 100",
       "legendFormat": "open"
      },
      {
       "expr": "go_sql_in_use_connections{job=\"$job\"} / go_sql_max_open_connections{job=\"$job\"} * 100",
       "legendFormat": "in_use"
      },
      {
       "expr": "increase(go_sql_wait_count_total{job=\"$job\"}[$__interval]) / go_sql_max_open_connections{job=\"$job\"} * 100",
       "legendFormat": "block"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_sys_bytes{job=\"$job\"}",
       "legendFormat": "go_memstats_sys_bytes"
      },
      {
       "expr": "process_resident_memory_bytes{job=\"$job\"}",
       "legendFormat": "process_resident_memory_bytes"
      },
      {
       "expr": "process_virtual_memory_bytes{job=\"$job\"}",
       "legendFormat": "process_virtual_memory_bytes"
      }
     ]
    },
    {
     "title": "Fd Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{job=\"$job\"}",
       "legendFormat": "process_open_fds"
      }
     ]
    },
    {
     "title": "Goroutine Pool Tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(go_pool_submitted_tasks_total{job=\"$job\"}[$__interval])",
       "legendFormat": "submitted"
      },
      {
       "expr": "increase(go_pool_failed_tasks_total{job=\"$job\"}[$__interval])",
       "legendFormat": "failed"
      }
     ]
    },
    {
     "title": "Database Pool Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(go_sql_max_idle_closed_total{job=\"$job\"}[$__interval]) + increase(go_sql_max_idle_time_closed_total{job=\"$job\"}[$__interval]) + increase(go_sql_max_lifetime_closed_total{job=\"$job\"}[$__interval])",
       "legendFormat": "closed"
      }
     ]
    }
   ]
  },
  {
   "title": "Request: $request_method",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "request_method",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Request Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(increase(api_request_duration_seconds_bucket{job=\"$job\",method=\"$request_method\",path=~\"/v1/.*|/account/.*\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request Size",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "targets": [
      {
       "expr": "sum(increase(api_request_sizes_bucket{job=\"$job\",method=\"$request_method\",path=~\"/v1/.*|/account/.*\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response Size",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "targets": [
      {
       "expr": "sum(increase(api_response_sizes_bucket{job=\"$job\",method=\"$request_method\",path=~\"/v1/.*|/account/.*\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cron: $cron_job",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "cron_job",
   "targets": [
    {}
   ]
  },
  {
   "title": "Task Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum(increase(cron_task_duration_seconds_bucket{job=\"$job\",exported_job=\"${cron_job}CronExpr\"}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Scheduling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "tasks" } },
   "targets": [
    {
     "expr": "increase(cron_scheduled_tasks_total{job=\"$job\",exported_job=\"${cron_job}CronExpr\"}[$__interval])",
     "legendFormat": "scheduled"
    },
    {
     "expr": "increase(cron_scheduled_tasks_total{job=\"$job\",exported_job=\"${cron_job}CronExpr\"}[$__interval]) - increase(cron_succeeded_tasks_total{job=\"$job\",exported_job=\"${cron_job}CronExpr\"}[$__interval])",
     "legendFormat": "failed"
    },
    {
     "expr": "cron_processing_tasks{job=\"$job\",exported_job=\"${cron_job}CronExpr\"}",
     "legendFormat": "processing"
    }
   ]
  },
  {
   "title": "Go",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Off-Heap Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mspan_inuse_bytes{job=\"$job\"}",
       "legendFormat": "go_memstats_mspan_inuse_bytes"
      },
      {
       "expr": "go_memstats_mspan_sys_bytes{job=\"$job\"}",
       "legendFormat": "go_memstats_mspan_sys_bytes"
      },
      {
       "expr": "go_memstats_mcache_inuse_bytes{job=\"$job\"}",
       "legendFormat": "go_memstats_mcache_inuse_bytes"
      },
      {
       "expr": "go_memstats_mcache_sys_bytes{job=\"$job\"}",
       "legendFormat": "go_memstats_mcache_sys_bytes"
      },
      {
       "expr": "go_memstats_buck_hash_sys_bytes{job=\"$job\"}",
       "legendFormat": "go_memstats_buck_hash_sys_bytes"
      },
      {
       "expr": "go_memstats_gc_sys_bytes{job=\"$job\"}",
       "legendFormat": "go_memstats_gc_sys_bytes"
      },
      {
       "expr": "go_memstats_other_sys_bytes{job=\"$job\"}",
       "legendFormat": "go_memstats_other_sys_bytes"
      },
      {
       "expr": "go_memstats_next_gc_bytes{job=\"$job\"}",
       "legendFormat": "go_memstats_next_gc_bytes"
      }
     ]
    },
    {
     "title": "Heap Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"$job\"}",
       "legendFormat": "go_memstats_heap_alloc_bytes"
      },
      {
       "expr": "go_memstats_heap_sys_bytes{job=\"$job\"}",
       "legendFormat": "go_memstats_heap_sys_bytes"
      },
      {
       "expr": "go_memstats_heap_idle_bytes{job=\"$job\"}",
       "legendFormat": "go_memstats_heap_idle_bytes"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{job=\"$job\"}",
       "legendFormat": "go_memstats_heap_inuse_bytes"
      },
      {
       "expr": "go_memstats_heap_released_bytes{job=\"$job\"}",
       "legendFormat": "go_memstats_heap_released_bytes"
      }
     ]
    },
    {
     "title": "Stack Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{job=\"$job\"}",
       "legendFormat": "go_memstats_stack_inuse_bytes"
      },
      {
       "expr": "go_memstats_stack_sys_bytes{job=\"$job\"}",
       "legendFormat": "go_memstats_stack_sys_bytes"
      }
     ]
    },
    {
     "title": "Live Objects",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mallocs_total{job=\"$job\"} - go_memstats_frees_total{job=\"$job\"}",
       "legendFormat": "go_memstats_mallocs_total - go_memstats_frees_total"
      }
     ]
    },
    {
     "title": "Object Allocation Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "rate"
      }
     ]
    },
    {
     "title": "Object Dereference Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_lookups_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "rate"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{job=\"$job\"}",
       "legendFormat": "go_goroutines"
      }
     ]
    },
    {
     "title": "Memory Allocation Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "rate"
      }
     ]
    },
    {
     "title": "GC Duration Quantile",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{job=\"$job\"}",
       "legendFormat": "{{quantile}}"
      }
     ]
    }
   ]
  }
 ]
}